-- Apply to the PSA Supabase project before deploying the invite-enabled backend.
-- Existing employee accounts and tables are unchanged.
BEGIN;

CREATE TABLE IF NOT EXISTS public.employee_invitations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    token_hash varchar(64) NOT NULL UNIQUE,
    created_by integer NOT NULL REFERENCES public.users(id),
    created_at timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    revoked_at timestamp without time zone
);

CREATE INDEX IF NOT EXISTS employee_invitations_email_idx
    ON public.employee_invitations (email);

REVOKE ALL PRIVILEGES ON TABLE public.employee_invitations FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.employee_invitations_id_seq FROM anon, authenticated;
ALTER TABLE public.employee_invitations ENABLE ROW LEVEL SECURITY;

COMMIT;
